- name: Install Docker
  ansible.builtin.apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Start and enable Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Pull Fluent Bit Docker image
  ansible.builtin.docker_image:
    name: fluent/fluent-bit
    tag: latest
    source: pull

- name: Run Fluent Bit container
  ansible.builtin.docker_container:
    name: fluent-bit
    image: fluent/fluent-bit:latest
    state: started
    restart_policy: always
    ports:
      - "2020:2020"
      - "2021:2021"
    volumes:
      - /etc/fluent-bit:/fluent-bit/etc:ro
      - /var/log:/var/log:ro

- name: Install Node Exporter
  ansible.builtin.shell: |
    curl -LO https://github.com/prometheus/node_exporter/releases/download/v1.6.1/node_exporter-1.6.1.linux-amd64.tar.gz
    tar xvfz node_exporter-1.6.1.linux-amd64.tar.gz
    mv node_exporter-1.6.1.linux-amd64/node_exporter /usr/local/bin/
    rm -rf node_exporter-1.6.1.linux-amd64*
